### ISSUE TITLE
[FEATURE] Design and Implement Question Page for 3MMCQ Type question

### ISSUE THREAD

**Issue by NeerajHazarika** [NeerajHazarika/gre_helper#4]
## Task Description
Design a visually appealing Question Page for 3MMCQ Type question for the GRE Helper project using Figma and implement it in the React front-end of the application. The Question Page for SMCQ Type question should provide an intuitive user interface and showcase key features of the GRE Helper app.

## Design Requirements
- Create wireframes and design layouts for the Question Page for 3MMCQ Type question using Figma.
- Include question image placeholder; 3 option (A-C); prev, save & next, next, submit and end button, timer
- Ensure the design is responsive and compatible with different screen sizes.

## Implementation Requirements
- Convert the Figma design into a responsive React component structure.
- Utilize appropriate styling techniques (CSS, CSS-in-JS, or CSS frameworks) to match the design.
- Implement necessary functionality to interact with the Flask back-end APIs for fetching relevant data.

## Additional Notes
- The project uses React, Flask, and SQLite3.
- Ensure code quality and maintain best practices throughout the implementation.
- Collaborate with the team and follow the established Git workflow for seamless integration.

## Deliverables
- Figma design files for the 3MMCQ type page.
- React component structure for the home page implementation.
- Functioning integration with the Flask back-end for fetching data.

## Deadline
- The task should be completed by [deadline date].

## Related Issues and Pull Requests
- [Link to related issue or pull request, if applicable]

## Assignees
- [Tag relevant team members for assignment]

## Labels
Labels: design, implementation, enhancement, good first issue

**Comment by a-nnurag** [comment]
please assign the issue to me

**Comment by NeerajHazarika** [comment]
@a-nnurag assigned!

**Comment by NeerajHazarika** [comment]
@a-nnurag any updates ?

**Comment by a-nnurag** [comment]
I will continue with work from tomorrow I got to involved with dsa and to
much outing bcz of friends. I am back to campus now
